### ISSUE TITLE
qc_report.py checkdim feature

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#1219]
As per conversation with @tomwright01 , I'm doing to add a little dimension checking feature to qc report.

in `${STUDY}_settings.yml`:

```
checkdims:
    - T1: (x, y, z)
    - RST: (x, y, z)
    - EMP: (x, y, z)
...
    - T2: (x, y, z)
```

`qc_report.py` will use this information to compare any scan and the expected dimensions using `nibabel`. The results will be written to `qc/${subject}/checkdims_${full_file_name}.csv. If they don't match, it will write a 1 to this file, otherwise, it will write a 0.

Later, we can add this information to the qc dashboard.
