### ISSUE TITLE
switch functional fmri pipelines to use new epitome script

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#561]
+ improved registration
+ no longer using dilated pre-processing masks

**Comment by josephdviviano** [comment]
also, another script that has no low-passing (use for functional data).

**Comment by josephdviviano** [comment]
+ I'm going to run everyone through the same script that uses no low-passing or tr scrubbing but DOES use ICA-FIX, since most members of the lab prefer ICA to other more lo-fi methods.

**Comment by edickie** [comment]
Hooray!!

For EPI data coming from our scanner - I would grab this classifier
/projects/edickie/analysis/epicTIGR/epicTIGR.RData
A readme file to go with it is at:
/projects/edickie/analysis/epicTIGR/epicTIGR_README.md

Also, can I ask for mni transformed file to be resampled to 2x2x2 - that
way i can add an hcp transfer step...

**Comment by edickie** [comment]
Hey Joe, you might also want note some things from the pipeline run before
training FIX..

1) the BET mask was set to "normal"
2) I imported the T1->MNI transforms from the hcp folder (not necessary,
but it saves some time, and keeps things consistent if functional data is
pushed to cifti space)

**Comment by josephdviviano** [comment]
@edickie if you want this new pipeline to use your HCP code you will have to make your HCP stuff into scriptuit modules :)

**Comment by josephdviviano** [comment]
This is done -- **all** fmri data is now processed using this: https://github.com/TIGRLab/datman/blob/master/bin/dm-proc-fmri.py

The configuration file contains some information about which epitome script should be run on each type of file, in a structure that looks like this:

```
fmri:                                                                           
    imob:                                                                       
        export: ['filtered', 'MNI', 'volsmooth']                                
        pipeline: 'task.sh'                                                     
        tags: ['IMI', 'OBS']                                                    
        del: 4                                                                  
        tr: 3                                                                   
        dims: 3  
```
